

CREATE TABLE TABELA_DE_VENDAS
( 
NUMERO VARCHAR (5) NOT NULL,
DATA_VENDA DATE NULL,
CPF VARCHAR (5) NULL,
MATRICULA VARCHAR (5) NULL,
IMPOSTO FLOAT NULL,
PRIMARY KEY (NUMERO)
);

ALTER TABLE TABELA_DE_VENDAS
ADD CONSTRAINT FK_CLIENTES
FOREIGN KEY (CPF) REFERENCES CLIENTES(CPF);

ALTER TABLE TABELA_DE_VENDAS 
ADD CONSTRAINT FK_VENDEDORES 
FOREIGN KEY (MATRICULA) REFERENCES VENDEDORES (MATRICULA);

ALTER TABLE TABELA_DE_VENDAS
ALTER COLUMN MATRICULA VARCHAR (5) NOT NULL;
--___________________________________________________________________________________

CREATE TABLE TABELA_DE_ITENS_VENDIDOS
(
NUMERO VARCHAR (5) NOT NULL,
CODIGO VARCHAR (10) NOT NULL,
QUANTIDADE FLOAT NULL,
PRECO FLOAT NULL
PRIMARY KEY (NUMERO, CODIGO)
);

ALTER TABLE TABELA_DE_ITENS_VENDIDOS
ADD CONSTRAINT FK_NUMERO
FOREIGN KEY (NUMERO) REFERENCES TABELA_DE_VENDAS (NUMERO);

ALTER TABLE TABELA_DE_ITENS_VENDIDOS
ADD CONSTRAINT FK_PRODUTOS
FOREIGN KEY (CODIGO) REFERENCES PRODUTOS (CODIGO)

