CREATE TABLE TAB_FATURAMENTO
(DATA_VENDA DATE NULL,
TOTAL_VENDA FLOAT);

SELECT 
TV.DATA_VENDA,
SUM(TIV.QUANTIDADE * TIV.PRECO) AS TOTAL_VENDA --(AO COLOCAR sum DEVER COLOCAR UM GROUP BY)
FROM TABELA_DE_VENDAS TV --(LIGACAO)
INNER JOIN TABELA_DE_ITENS_VENDIDOS TIV --(LIGACAO)
ON TV.NUMERO = TIV.NUMERO --(COLUNA EM COMUM)
GROUP BY DATA_VENDA

SELECT * FROM CLIENTES

INSERT INTO TABELA_DE_VENDAS
VALUES 
('0100', '2018-05-15', '1471156710', '235', 0.18);

SELECT * FROM PRODUTOS

INSERT INTO TABELA_DE_ITENS_VENDIDOS
VALUES ('0100', '1000889', 100, 10)

-------------------------------------------------------------------------------------------------
SELECT 
TV.DATA_VENDA,
SUM(TIV.QUANTIDADE * TIV.PRECO) AS TOTAL_VENDA --(AO COLOCAR sum DEVER COLOCAR UM GROUP BY)
FROM TABELA_DE_VENDAS TV --(LIGACAO)
INNER JOIN TABELA_DE_ITENS_VENDIDOS TIV --(LIGACAO)
ON TV.NUMERO = TIV.NUMERO --(COLUNA EM COMUM)
GROUP BY DATA_VENDA

---------------------------------------------------------------------

INSERT INTO TABELA_DE_VENDAS
VALUES 
('0101', '2018-05-15', '1471156710', '235', 0.18);


INSERT INTO TABELA_DE_ITENS_VENDIDOS
VALUES ('0101', '1000889', 100, 10)

-------------------------------------------------
INSERT INTO TAB_FATURAMENTO
SELECT 
TV.DATA_VENDA,
SUM(TIV.QUANTIDADE * TIV.PRECO) AS TOTAL_VENDA --(AO COLOCAR sum DEVER COLOCAR UM GROUP BY)
FROM TABELA_DE_VENDAS TV --(LIGACAO)
INNER JOIN TABELA_DE_ITENS_VENDIDOS TIV --(LIGACAO)
ON TV.NUMERO = TIV.NUMERO --(COLUNA EM COMUM)
GROUP BY DATA_VENDA

SELECT * FROM TAB_FATURAMENTO

INSERT INTO TABELA_DE_VENDAS
VALUES 
('0102', '2018-05-15', '1471156710', '235', 0.18);


INSERT INTO TABELA_DE_ITENS_VENDIDOS
VALUES ('0102', '1000889', 100, 10)


DELETE FROM TAB_FATURAMENTO;

INSERT INTO TAB_FATURAMENTO
SELECT 
TV.DATA_VENDA,
SUM(TIV.QUANTIDADE * TIV.PRECO) AS TOTAL_VENDA --(AO COLOCAR sum DEVER COLOCAR UM GROUP BY)
FROM TABELA_DE_VENDAS TV --(LIGACAO)
INNER JOIN TABELA_DE_ITENS_VENDIDOS TIV --(LIGACAO)
ON TV.NUMERO = TIV.NUMERO --(COLUNA EM COMUM)
GROUP BY DATA_VENDA

SELECT * FROM TAB_FATURAMENTO
--------------------------------------------------------------------------------------

SELECT * FROM TAB_FATURAMENTO;

INSERT INTO TABELA_DE_VENDAS
VALUES 
('0103', '2018-05-15', '1471156710', '235', 0.18);


INSERT INTO TABELA_DE_ITENS_VENDIDOS
VALUES ('0103', '1000889', 100, 10);


DELETE FROM TAB_FATURAMENTO;

INSERT INTO TAB_FATURAMENTO
SELECT 
TV.DATA_VENDA,
SUM(TIV.QUANTIDADE * TIV.PRECO) AS TOTAL_VENDA --(AO COLOCAR sum DEVER COLOCAR UM GROUP BY)
FROM TABELA_DE_VENDAS TV --(LIGACAO)
INNER JOIN TABELA_DE_ITENS_VENDIDOS TIV --(LIGACAO)
ON TV.NUMERO = TIV.NUMERO --(COLUNA EM COMUM)
GROUP BY DATA_VENDA;

SELECT * FROM TAB_FATURAMENTO;


---------------------------------------------------------------

SELECT * FROM TAB_FATURAMENTO;

INSERT INTO TABELA_DE_VENDAS
VALUES 
('0104', '2018-05-16', '1471156710', '235', 0.18);


INSERT INTO TABELA_DE_ITENS_VENDIDOS
VALUES ('0104', '1000889', 100, 10);


DELETE FROM TAB_FATURAMENTO;

INSERT INTO TAB_FATURAMENTO
SELECT 
TV.DATA_VENDA,
SUM(TIV.QUANTIDADE * TIV.PRECO) AS TOTAL_VENDA --(AO COLOCAR sum DEVER COLOCAR UM GROUP BY)
FROM TABELA_DE_VENDAS TV --(LIGACAO)
INNER JOIN TABELA_DE_ITENS_VENDIDOS TIV --(LIGACAO)
ON TV.NUMERO = TIV.NUMERO --(COLUNA EM COMUM)
GROUP BY DATA_VENDA;

SELECT * FROM TAB_FATURAMENTO;

----------------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------

CREATE TRIGGER TG_ITENS_VENDIDOS
ON TABELA_DE_ITENS_VENDIDOS
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
DELETE FROM TAB_FATURAMENTO;

INSERT INTO TAB_FATURAMENTO
SELECT 
TV.DATA_VENDA,
SUM(TIV.QUANTIDADE * TIV.PRECO) AS TOTAL_VENDA --(AO COLOCAR sum DEVER COLOCAR UM GROUP BY)
FROM TABELA_DE_VENDAS TV --(LIGACAO)
INNER JOIN TABELA_DE_ITENS_VENDIDOS TIV --(LIGACAO)
ON TV.NUMERO = TIV.NUMERO --(COLUNA EM COMUM)
GROUP BY TV.DATA_VENDA;

END;

-------------------------------------------------------------
SELECT * FROM TAB_FATURAMENTO;

INSERT INTO TABELA_DE_VENDAS
VALUES 
('0105', '2018-05-16', '1471156710', '235', 0.18);


INSERT INTO TABELA_DE_ITENS_VENDIDOS
VALUES ('0105', '1000889', 150, 10);

SELECT * FROM TAB_FATURAMENTO;

INSERT INTO TABELA_DE_VENDAS
VALUES 
('0106', '2018-05-16', '1471156710', '235', 0.18);


INSERT INTO TABELA_DE_ITENS_VENDIDOS
VALUES ('0106', '1000889', 150, 10);


SELECT * FROM TAB_FATURAMENTO;

UPDATE TABELA_DE_ITENS_VENDIDOS SET QUANTIDADE = 200 WHERE NUMERO = '0106'

DELETE FROM TABELA_DE_ITENS_VENDIDOS WHERE NUMERO = '0106'
---------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------------
-- O SQL abaixo calcula a idade em anos baseado na data atual:

SELECT [CPF], [IDADE], [DATA_NASCIMENTO], 
    DATEDIFF(YEAR, [DATA_NASCIMENTO], GETDATE()) 
FROM CLIENTES

--Levando em consideração a situação posta acima: construa uma TRIGGER, de nome TG_CLIENTES_IDADE, que atualize as idades dos 
--clientes, na tabela de clientes, toda vez que a tabela sofrer uma inclusão, alteração ou exclusão.


SELECT * FROM CLIENTES

CREATE TRIGGER TG_CLIENTES_IDADE
ON CLIENTES
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
UPDATE CLIENTES SET IDADE = 
       DATEDIFF(YEAR, [DATA_NASCIMENTO], GETDATE()) 

END;

