UPDATE SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS SET 
PRECO_DE_LISTA = PRECO_DE_LISTA * 1.20;

SELECT 
A.CODIGO AS CODIGO_MINHA_TABELA, A.PRECO_LISTA AS PRECO_MINHA_TABELA, 
B.CODIGO_DO_PRODUTO AS CODIGO_TABELA_APOIO, B.PRECO_DE_LISTA AS PRECO_TABELA_APOIO 
FROM PRODUTOS A 
INNER JOIN SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS B 
ON A.CODIGO = B.CODIGO_DO_PRODUTO;

UPDATE A SET A.PRECO_LISTA = B.PRECO_DE_LISTA 
FROM PRODUTOS A 
INNER JOIN SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS B 
ON A.CODIGO = B.CODIGO_DO_PRODUTO;

--- ou, SE DARA O MESMO RESULTADO

MERGE INTO PRODUTOS A
USING SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS B 
ON A.CODIGO = B.CODIGO_DO_PRODUTO
WHEN MATCHED THEN 
UPDATE SET A.PRECO_LISTA = B.PRECO_DE_LISTA;

-----------------------------------------------------------------------

--Agora que já passamos por alguns passos, resolva o problema do exercício anterior usando MERGE.

--Repetindo o enunciado:

--Podemos observar que os vendedores possuem bairros associados a eles.
--Vamos aumentar em 30% o volume de compra dos clientes que possuem, em seus endereços, bairros onde os vendedores possuam escritórios.


SELECT VOLUME_COMPRA FROM CLIENTES A
INNER JOIN VENDEDORES B
ON A.[BAIRRO] = B.[BAIRRO]


UPDATE A SET A.VOLUME_COMPRA = A.VOLUME_COMPRA * 1.30
FROM CLIENTES A
INNER JOIN VENDEDORES B
ON A.[BAIRRO] = B.[BAIRRO]

-- OU

MERGE INTO CLIENTES A
USING VENDEDORES B
ON A.[BAIRRO] = B.[BAIRRO]
WHEN MATCHED THEN 
UPDATE SET A.VOLUME_COMPRA = A.VOLUME_COMPRA * 1.30;

