SELECT COUNT(*) FROM [NOTAS FISCAIS] WHERE NUMERO = 98

SELECT MIN(NUMERO), MAX(NUMERO) FROM [NOTAS FISCAIS]

IF OBJECT_ID('TABELA DE NUMEROS', 'U') IS NOT NULL DROP TABLE [TABELA DE NUMEROS];
CREATE TABLE [TABELA DE NUMEROS] ([NUMERO] INT, [STATUS] VARCHAR(20));

DECLARE @NUMERO_INICIAL_SEQUENCIA INT, @NUMERO_FINAL_SEQUENCIA INT;
DECLARE @TESTE_NOTA_FISCAL INT;
SET @NUMERO_INICIAL_SEQUENCIA = 1;
SET @NUMERO_FINAL_SEQUENCIA = 100000;

WHILE @NUMERO_INICIAL_SEQUENCIA <= @NUMERO_FINAL_SEQUENCIA
BEGIN
  SELECT @TESTE_NOTA_FISCAL = COUNT(*) FROM [NOTAS FISCAIS] WHERE NUMERO = @NUMERO_INICIAL_SEQUENCIA
  IF @TESTE_NOTA_FISCAL = 1
    INSERT INTO [TABELA DE NUMEROS] ([NUMERO], [STATUS]) VALUES (@NUMERO_INICIAL_SEQUENCIA, 'É NOTA FISCAL');
ELSE
    INSERT INTO [TABELA DE NUMEROS] ([NUMERO], [STATUS]) VALUES (@NUMERO_INICIAL_SEQUENCIA, 'NÃP É NOTA FISCAL' );
	SET @NUMERO_INICIAL_SEQUENCIA = @NUMERO_INICIAL_SEQUENCIA + 1;
END;

SELECT * FROM [TABELA DE NUMEROS]

--___________________________________________________________________________________________________________________________________

--DESAFIO

IF OBJECT_ID('TABELANOTAS','U') IS NOT NULL
DROP TABLE TABELANOTAS

CREATE TABLE TABELANOTAS (DATA DATE, NUMNOTAS INT)

DECLARE @DATAINICIAL DATE
DECLARE @DATAFINAL DATE
DECLARE @NUMNOTAS INT
SET @DATAINICIAL = '20170101'
SET @DATAFINAL = '20170110'
WHILE @DATAINICIAL <= @DATAFINAL
BEGIN
    SELECT @NUMNOTAS = COUNT(*) FROM [NOTAS FISCAIS] 
        WHERE DATA = @DATAINICIAL
    INSERT INTO TABELANOTAS (DATA, NUMNOTAS) 
        VALUES (@DATAINICIAL, @NUMNOTAS)
    SELECT @DATAINICIAL = DATEADD(DAY, 1, @DATAINICIAL)
END

SELECT * FROM TABELANOTAS