

SELECT * FROM [TABELA DE CLIENTES]
SELECT COUNT(*) FROM [TABELA DE CLIENTES]


SELECT X.CPF, X.NOME
FROM (
SELECT ROW_NUMBER () OVER (ORDER BY CPF) AS RowNum, *
FROM [TABELA DE CLIENTES]
) X
WHERE X.RowNum = 5




DECLARE @CPF VARCHAR (11);
DECLARE @NOME VARCHAR (100);
DECLARE @NUMERO_CLIENTES INT;
DECLARE @I INT;

SELECT @NUMERO_CLIENTES = COUNT(*) FROM [TABELA DE CLIENTES]
SET @I = 1;

WHILE @I <= @NUMERO_CLIENTES
BEGIN
    SELECT @CPF = X.CPF, @NOME = X.NOME
    FROM ( SELECT ROW_NUMBER () OVER (ORDER BY CPF) AS RowNum, * FROM [TABELA DE CLIENTES]) X
    WHERE X.RowNum = @I;
	PRINT @CPF + ' - ' + @NOME;
	SET @I = @I + 1;
END;


--__________________________________________________________________________________________________________________

--DESAfio
SELECT * FROM [TABELA DE CLIENTES]

--SELECT
--SUM([ITENS NOTAS FISCAIS].QUANTIDADE * [ITENS NOTAS FISCAIS].[PREÇO])
--FROM [NOTAS FISCAIS]
--INNER JOIN [ITENS NOTAS FISCAIS]
--ON [NOTAS FISCAIS].NUMERO = [ITENS NOTAS FISCAIS].NUMERO
--WHERE [NOTAS FISCAIS].CPF = '1471156710'
--AND YEAR([NOTAS FISCAIS].DATA) = 2015 AND MONTH([NOTAS FISCAIS].DATA) = 1;

DECLARE @CPF VARCHAR (11);
DECLARE @NOME VARCHAR (100);
DECLARE @NUMERO_CLIENTES INT;
DECLARE @I INT;
DECLARE @MES INT, @ANO INT;
DECLARE @TOTAL_DE_VENDAS FLOAT;
DECLARE @TABELA_FINAL TABLE (CPF VARCHAR(11), NOME VARCHAR(100), MES INT, ANO INT, VALOR_TOTAL FLOAT)


SET @ANO = 2015;
SET @MES = 2;

SELECT @NUMERO_CLIENTES = COUNT(*) FROM [TABELA DE CLIENTES]
SET @I = 1;

WHILE @I <= @NUMERO_CLIENTES
BEGIN
    SELECT @CPF = X.CPF, @NOME = X.NOME
    FROM ( SELECT ROW_NUMBER () OVER (ORDER BY CPF) AS RowNum, * FROM [TABELA DE CLIENTES]) X
    WHERE X.RowNum = @I;
	
	SELECT
    @TOTAL_DE_VENDAS = SUM([ITENS NOTAS FISCAIS].QUANTIDADE * [ITENS NOTAS FISCAIS].[PREÇO])
    FROM [NOTAS FISCAIS]
    INNER JOIN [ITENS NOTAS FISCAIS]
    ON [NOTAS FISCAIS].NUMERO = [ITENS NOTAS FISCAIS].NUMERO
    WHERE [NOTAS FISCAIS].CPF = @CPF
    AND YEAR([NOTAS FISCAIS].DATA) = @ANO AND MONTH([NOTAS FISCAIS].DATA) = @MES;

	INSERT INTO @TABELA_FINAL VALUES (@CPF, @NOME, @MES, @ANO, @TOTAL_DE_VENDAS);
		PRINT 'Vendas para ' + @CPF + ' - ' + @NOME + ' NO MÊS ' + CONVERT(VARCHAR(2), @MES) + ' E ANO ' + CONVERT(VARCHAR(4),@ANO) + ' FOI DE ' + TRIM(STR(@TOTAL_DE_VENDAS, 15, 2));
        SET @I = @I + 1;

END;

SELECT * FROM @TABELA_FINAL
