SELECT COUNT(*) FROM TABELA_DE_CLIENTES

--16 CLIENTE -----> 7 CLIENTES POSSUEM NOS SEUS BAIRROS SEUS VENDEDORES

SELECT COUNT(*) FROM TABELA_DE_VENDEDORES

--4 CLIENTE -----> 3 VENDEDORE POSSUEM NOS SEUS BAIRROS CLIENTES
-- QUAL É O VENDEDOR QUE NAO TEM CLIENTE NO SEU BAIRRO:


SELECT
TV.NOME AS NOME_DO_VENDEDOR,
TV.BAIRRO AS BAIRRO_DO_VENDEDOR,
TC.BAIRRO AS BAIRRO_DO_CLIENTE,
TC.NOME AS NOME_DO_CLIENTE
FROM 
TABELA_DE_CLIENTES TC
INNER JOIN
TABELA_DE_VENDEDORES TV
ON TC.BAIRRO = TV.BAIRRO


-- QUAL É O VENDEDOR QUE NAO TEM CLIENTE NO SEU BAIRRO:
SELECT DISTINCT
TV.NOME AS NOME_DO_VENDEDOR,
TV.BAIRRO AS BAIRRO_DO_VENDEDOR,
TC.BAIRRO AS BAIRRO_DO_CLIENTE,
TC.NOME AS NOME_DO_CLIENTE
FROM 
TABELA_DE_CLIENTES TC
RIGHT JOIN
TABELA_DE_VENDEDORES TV
ON TC.BAIRRO = TV.BAIRRO
WHERE TC.NOME IS NULL

-- R: ROBERTA MARTINS EM COPACABANA


-- QUAIS SAO OS CLIENTES QUE NAO TEM VENDEDORES EM SEUS BAIRROS:::

SELECT DISTINCT
TV.NOME AS NOME_DO_VENDEDOR,
TV.BAIRRO AS BAIRRO_DO_VENDEDOR,
TC.BAIRRO AS BAIRRO_DO_CLIENTE,
TC.NOME AS NOME_DO_CLIENTE
FROM 
TABELA_DE_CLIENTES TC
LEFT JOIN
TABELA_DE_VENDEDORES TV
ON TC.BAIRRO = TV.BAIRRO
WHERE TV.NOME IS NULL

--R: 9 CLIENTES
--Fernando Cavalcante
--Juliana Silva
--Fabio Carvalho
--Marcelo Mattos
--Edson Meilelles
--Abel Silva 
--Marcos Nogueira
--Petra Oliveira
--Walber Lontra

SELECT DISTINCT
TV.NOME AS NOME_DO_VENDEDOR,
TV.BAIRRO AS BAIRRO_DO_VENDEDOR,
TC.BAIRRO AS BAIRRO_DO_CLIENTE,
TC.NOME AS NOME_DO_CLIENTE
FROM 
TABELA_DE_CLIENTES TC
FULL JOIN
TABELA_DE_VENDEDORES TV
ON TC.BAIRRO = TV.BAIRRO
