SELECT * FROM TABELA_DE_VENDEDORES;

SELECT * FROM NOTAS_FISCAIS;

SELECT MATRICULA, COUNT(*) AS NUMERO_DE_NOTAS_FISCAIS 
FROM NOTAS_FISCAIS 
GROUP BY MATRICULA;

SELECT NOTAS_FISCAIS.MATRICULA, TABELA_DE_VENDEDORES.NOME, COUNT(*) AS NUMERO_DE_NOTAS
FROM NOTAS_FISCAIS 
INNER JOIN TABELA_DE_VENDEDORES
ON NOTAS_FISCAIS.MATRICULA = TABELA_DE_VENDEDORES.MATRICULA
GROUP BY NOTAS_FISCAIS.MATRICULA, TABELA_DE_VENDEDORES.NOME;

--FORMA SIMPLIFICADA:

SELECT NF.MATRICULA, TV.NOME, COUNT(*) AS NUMERO_DE_NOTAS
FROM NOTAS_FISCAIS NF 
INNER JOIN TABELA_DE_VENDEDORES TV
ON NF.MATRICULA = TV.MATRICULA
GROUP BY NF.MATRICULA, TV.NOME;

--ABAIXO, BOA PRATICA PARA FAZER O joiN, DEVIDO A HIERARQUIA, Isso significa que a tabela TABELA_DE_VENDEDORES 
--sozinha existe, eu posso ter cadastro de vendedores que não tem nenhuma nota fiscal, mas para existir a tabela
--NOTAS_FISCAIS, por causa do campo MATRICULA, eu preciso que TABELA_DE_VENDEDORES exista. 
SELECT NF.MATRICULA, TV.NOME, COUNT(*) AS NUMERO_DE_NOTAS
FROM TABELA_DE_VENDEDORES TV
INNER JOIN NOTAS_FISCAIS NF  
ON NF.MATRICULA = TV.MATRICULA
GROUP BY NF.MATRICULA, TV.NOME;

--Em exercícios anteriores, pretendíamos obter os produtos que venderam mais que 394000 litros e para isso executamos a 
--seguinte consulta.

--SELECT CODIGO_DO_PRODUTO, SUM(QUANTIDADE) AS QUANTIDADE FROM ITENS_NOTAS_FISCAIS 
--GROUP BY CODIGO_DO_PRODUTO HAVING SUM(QUANTIDADE) > 394000 
--ORDER BY SUM(QUANTIDADE) DESC;

--Dito isso, e levando em consideração os comandos da consulta, desejamos que na resposta desta consulta apareça não somente o 
--código do produto, mas também o nome do produto.
--Com este cenário em mente, como podemos resolver esse tipo de solicitação?

SELECT INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO, SUM(INF.QUANTIDADE) AS QUANTIDADE 
FROM ITENS_NOTAS_FISCAIS  INF
INNER JOIN TABELA_DE_PRODUTOS TP 
ON INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO
GROUP BY INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO HAVING SUM(INF.QUANTIDADE) > 394000 
ORDER BY SUM(INF.QUANTIDADE) DESC;


SELECT INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO, SUM(INF.QUANTIDADE) AS QUANTIDADE 
FROM ITENS_NOTAS_FISCAIS  INF
INNER JOIN TABELA_DE_PRODUTOS TP 
ON INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO
GROUP BY INF.CODIGO_DO_PRODUTO HAVING SUM(INF.QUANTIDADE) > 394000 
ORDER BY SUM(INF.QUANTIDADE) DESC;