
SELECT DISTINCT BAIRRO FROM TABELA_DE_CLIENTES;
-- 12 BAIRRO RELACIONADOS COM CLIENTES


SELECT DISTINCT BAIRRO FROM TABELA_DE_VENDEDORES;
-- 4 BAIRRO RELACIONADOS COM VENDEDORES
 
 SELECT DISTINCT BAIRRO FROM TABELA_DE_CLIENTES
 UNION
 SELECT DISTINCT BAIRRO FROM TABELA_DE_VENDEDORES;
 -- 13 BAIRRO RELACIONADOS COM VENDEDORES E CLIENTES


  SELECT DISTINCT BAIRRO FROM TABELA_DE_CLIENTES
 UNION ALL
 SELECT DISTINCT BAIRRO FROM TABELA_DE_VENDEDORES;
 -- 16 BAIRRO RELACIONADOS COM VENDEDORES E CLIENTES

 
  SELECT DISTINCT BAIRRO, 'CLIENTE' AS ORIGEM FROM TABELA_DE_CLIENTES
 UNION ALL
 SELECT DISTINCT BAIRRO, 'VENDEDORES' AS ORIGEM FROM TABELA_DE_VENDEDORES;
 -- 16 BAIRRO RELACIONADOS COM VENDEDORES E CLIENTES

   SELECT DISTINCT BAIRRO, 'CLIENTE' AS ORIGEM FROM TABELA_DE_CLIENTES
 UNION
 SELECT DISTINCT BAIRRO, 'VENDEDORES' AS ORIGEM FROM TABELA_DE_VENDEDORES;
  -- 16 BAIRRO RELACIONADOS COM VENDEDORES E CLIENTES