
--USANDO TOP
SELECT * FROM TABELA_DE_PRODUTOS;

SELECT DISTINCT TOP 5 * FROM TABELA_DE_PRODUTOS;

SELECT TOP 5 * FROM TABELA_DE_PRODUTOS;

SELECT TOP 5 * FROM TABELA_DE_PRODUTOS WHERE SABOR = 'MACA';

--qual é o comando SQL para listar as 10 primeiras vendas do dia 01/10/2017

SELECT TOP 10 * FROM NOTAS_FISCAIS WHERE DATA_VENDA = '2017/10/01';

--USANDO ORDER BY
SELECT * FROM TABELA_DE_PRODUTOS;

--ORDENA O PRODUTO PELO MAIOR PRECO
SELECT * FROM TABELA_DE_PRODUTOS ORDER BY PRECO_DE_LISTA DESC;


SELECT * FROM TABELA_DE_PRODUTOS ORDER BY NOME_DO_PRODUTO ASC;

SELECT * FROM TABELA_DE_PRODUTOS ORDER BY EMBALAGEM, NOME_DO_PRODUTO;

SELECT * FROM TABELA_DE_PRODUTOS ORDER BY EMBALAGEM DESC, NOME_DO_PRODUTO DESC;



SELECT TOP 5 * FROM TABELA_DE_PRODUTOS ORDER BY PRECO_DE_LISTA DESC;


--Qual foi a maior venda do produto "Linha Refrescante - 1 Litro - Morango/Limao" em quantidade?

SELECT CODIGO_DO_PRODUTO FROM TABELA_DE_PRODUTOS WHERE NOME_DO_PRODUTO = 'Linha Refrescante - 1 Litro - Morango/Limao';
SELECT * FROM ITENS_NOTAS_FISCAIS WHERE CODIGO_DO_PRODUTO = '1101035' ORDER BY QUANTIDADE DESC;

--OU 

SELECT * FROM TABELA_DE_PRODUTOS WHERE nome_do_produto = 'Linha Refrescante - 1 Litro - Morango/Limao';
SELECT * FROM ITENS_NOTAS_FISCAIS WHERE codigo_do_produto = '1101035' ORDER BY QUANTIDADE DESC;