SELECT CONVERT(VARCHAR(10), GETDATE(), 121)

SELECT CONVERT(VARCHAR(25), GETDATE(), 121)

SELECT * FROM TABELA_DE_CLIENTES

SELECT DATA_DE_NASCIMENTO, CONVERT(VARCHAR(25), DATA_DE_NASCIMENTO, 121) FROM TABELA_DE_CLIENTES

SELECT DATA_DE_NASCIMENTO, CONVERT(VARCHAR(25), DATA_DE_NASCIMENTO, 106) AS TIPOS_DE_MASCARA FROM TABELA_DE_CLIENTES

SELECT NOME_DO_PRODUTO, PRECO_DE_LISTA FROM TABELA_DE_PRODUTOS
SELECT NOME_DO_PRODUTO, CONCAT('O preço de lista é: R$ ', PRECO_DE_LISTA) AS PRECO FROM TABELA_DE_PRODUTOS
--OU
SELECT NOME_DO_PRODUTO, CONCAT('O preço de lista é: ', CAST(PRECO_DE_LISTA AS VARCHAR(10))) AS PRECO FROM TABELA_DE_PRODUTOS


--Queremos construir um SQL cujo resultado seja para cada cliente:

--"O cliente João da Silva comprou R$ 121222,12 no ano de 2016".
--Faça isso somente para o ano de 2016.

--Dica: Procure na documentação como se usa a função STR para converter um número FLOAT em texto.

SELECT * FROM TABELA_DE_CLIENTES

SELECT 'O cliente ' + TC.NOME + ' comprou R$ ' + 
TRIM(STR(SUM(INF.QUANTIDADE * INF.PRECO) ,10,2)) + ' no ano de ' + DATENAME(YEAR, NF.DATA_VENDA)
FROM NOTAS_FISCAIS NF
INNER JOIN ITENS_NOTAS_FISCAIS INF ON NF.NUMERO = INF.NUMERO
INNER JOIN TABELA_DE_CLIENTES TC ON NF.CPF = TC.CPF
WHERE YEAR(NF.DATA_VENDA) = '2016'
GROUP BY TC.NOME, NF.DATA_VENDA;

