

CREATE TABLE #TABELA01 (ID VARCHAR (10), NOME VARCHAR(30));
INSERT INTO #TABELA01 VALUES ('1', 'JOAO');
INSERT INTO #TABELA01 VALUES ('2', 'KATIA');

SELECT * FROM #TABELA01



CREATE TABLE ##TABELA02 (ID VARCHAR (10), NOME VARCHAR(30));
INSERT INTO ##TABELA02 VALUES ('1', 'JOAO');
INSERT INTO ##TABELA02 VALUES ('2', 'KATIA');

SELECT * FROM ##TABELA02