 --NAO APARECE EM OUTRA QUERY
SELECT * FROM #TABELA01

-- CONSEGUE MANIPULAR OS DADOS EM OUTRA QUERY. SO AO APARECE QUANDO DERRUBA A CONEXAO COM O SERVIDOR
INSERT INTO ##TABELA02 VALUES ('3', 'JORGE');
SELECT * FROM ##TABELA02

--_________________________________________________________________________
DECLARE @NUMERO_INICIAL_SEQUENCIA INT, @NUMERO_FINAL_SEQUENCIA INT;
DECLARE @TESTE_NOTA_FISCAL INT;
DECLARE @TABELA_DE_NUMEROS TABLE ([NUMERO] INT, [STATUS] VARCHAR(20));

SET @NUMERO_INICIAL_SEQUENCIA = 1;
SET @NUMERO_FINAL_SEQUENCIA = 100000;

WHILE @NUMERO_INICIAL_SEQUENCIA <= @NUMERO_FINAL_SEQUENCIA
BEGIN
        SELECT @TESTE_NOTA_FISCAL = COUNT(*) FROM [NOTAS FISCAIS] WHERE 
        NUMERO = @NUMERO_INICIAL_SEQUENCIA;
        IF @TESTE_NOTA_FISCAL = 1
             INSERT INTO @TABELA_DE_NUMEROS ([NUMERO], [STATUS]) 
             VALUES (@NUMERO_INICIAL_SEQUENCIA, 'É NOTA FISCAL');
        ELSE
             INSERT INTO @TABELA_DE_NUMEROS ([NUMERO], [STATUS]) 
             VALUES (@NUMERO_INICIAL_SEQUENCIA, 'NÃO É NOTA FISCAL');
        SET @NUMERO_INICIAL_SEQUENCIA = @NUMERO_INICIAL_SEQUENCIA + 1;
END;

SELECT * FROM @TABELA_DE_NUMEROS;

SELECT * FROM @TABELA_DE_NUMEROS;
--_______________________________________________________________________________________________________________________

DECLARE @NUMERO_INICIAL_SEQUENCIA INT, @NUMERO_FINAL_SEQUENCIA INT;
DECLARE @TESTE_NOTA_FISCAL INT;
DECLARE @TABELA_DE_NUMEROS TABLE ([NUMERO] INT, [STATUS] VARCHAR(20));
CREATE TABLE #TABELA_DE_NUMEROS ([NUMERO] INT, [STATUS] VARCHAR(20))

SET @NUMERO_INICIAL_SEQUENCIA = 1;
SET @NUMERO_FINAL_SEQUENCIA = 100000;

WHILE @NUMERO_INICIAL_SEQUENCIA <= @NUMERO_FINAL_SEQUENCIA

BEGIN
        SELECT @TESTE_NOTA_FISCAL = COUNT(*) FROM [NOTAS FISCAIS] WHERE 
        NUMERO = @NUMERO_INICIAL_SEQUENCIA;
        IF @TESTE_NOTA_FISCAL = 1
		  BEGIN
              INSERT INTO @TABELA_DE_NUMEROS ([NUMERO], [STATUS]) 
              VALUES (@NUMERO_INICIAL_SEQUENCIA, 'É NOTA FISCAL');
            
			  INSERT INTO #TABELA_DE_NUMEROS ([NUMERO], [STATUS]) 
              VALUES (@NUMERO_INICIAL_SEQUENCIA, 'É NOTA FISCAL');
	      END;
      
	  ELSE
	  
	      BEGIN
              INSERT INTO @TABELA_DE_NUMEROS ([NUMERO], [STATUS]) 
              VALUES (@NUMERO_INICIAL_SEQUENCIA, 'NÃO É NOTA FISCAL');

			  INSERT INTO #TABELA_DE_NUMEROS ([NUMERO], [STATUS]) 
              VALUES (@NUMERO_INICIAL_SEQUENCIA, 'NÃO É NOTA FISCAL');
		  END;
     
	 SET @NUMERO_INICIAL_SEQUENCIA = @NUMERO_INICIAL_SEQUENCIA + 1;

END;

SELECT * FROM @TABELA_DE_NUMEROS;

SELECT * FROM #TABELA_DE_NUMEROS;