gfb --TABELA TEMPORARIA - DESAFIO - TABELA DE CLIENTES

SELECT * FROM [TABELA DE PRODUTOS]

SELECT COUNT(*) FROM [TABELA DE PRODUTOS]

DECLARE @CODIGO VARCHAR(11);
DECLARE @NOME_DO_PRODUTO VARCHAR(100);
DECLARE @NUMERO_CLIENTES INT;
DECLARE @I INT;

SELECT @NUMERO_CLIENTES = COUNT(*) FROM [TABELA DE PRODUTOS];
SET @I = 1;
WHILE @I <= @NUMERO_CLIENTES

BEGIN
        SELECT @CODIGO = X.[CODIGO DO PRODUTO], @NOME_DO_PRODUTO = X.[NOME DO PRODUTO]
        FROM ( SELECT Row_Number() Over (Order By [CODIGO DO PRODUTO]) as RowNum, * FROM [TABELA DE PRODUTOS]) X
        WHERE X.RowNum = @I;
        PRINT @CODIGO + ' - ' + @NOME_DO_PRODUTO;
        SET @I = @I + 1;
END;

