
SELECT * FROM PRODUTOS ORDER BY CODIGO

SELECT * FROM SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS ORDER BY CODIGO_DO_PRODUTO

UPDATE SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS SET PRECO_DE_LISTA =  PRECO_DE_LISTA * 1.20



SELECT
A.CODIGO AS CODIGO_MINHA_TABELA, A.PRECO_LISTA AS PRECO_MINHA_TABELA,
B.CODIGO_DO_PRODUTO AS CODIGO_TABELA_APOIO, B.PRECO_DE_LISTA AS PRECO_TABELA_APOIO
FROM PRODUTOS A
INNER JOIN SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS B
ON A.CODIGO = B.CODIGO_DO_PRODUTO


UPDATE A SET A.PRECO_LISTA = B.PRECO_DE_LISTA 
FROM PRODUTOS A
INNER JOIN SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS B
ON A.CODIGO = B.CODIGO_DO_PRODUTO

-------------------------------------------------------------------------------------

--Podemos observar que os vendedores possuem bairros associados a eles. Vamos aumentar em 30% o volume de compra dos 
--clientes que possuem, em seus endereços, bairros onde os vendedores possuam escritórios.

--Dica: vamos usar um UPDATE com FROM, usando o seguinte INNER JOIN:

SELECT * FROM CLIENTES ORDER BY BAIRRO

SELECT * FROM VENDEDORES ORDER BY BAIRRO

SELECT VOLUME_COMPRA FROM CLIENTES A
INNER JOIN VENDEDORES B
ON A.[BAIRRO] = B.[BAIRRO]


UPDATE A SET A.VOLUME_COMPRA = A.VOLUME_COMPRA * 1.30
FROM CLIENTES A
INNER JOIN VENDEDORES B
ON A.[BAIRRO] = B.[BAIRRO]

-- ou

UPDATE A SET A.[VOLUME DE COMPRA] = 
    A.[VOLUME DE COMPRA] * 1.30
FROM [dbo].[CLIENTES] A 
INNER JOIN [dbo].[VENDEDORES] B
ON A.[BAIRRO] = B.[BAIRRO]