
DECLARE @LIMITE_MINIMO INT, @LIMITE_MAXIMO INT
DECLARE @TABELA_NUMEROS TABLE ([NUMERO] INT, [STATUS] VARCHAR (200))
DECLARE @CONTADOR_NOTAS INT

SET @LIMITE_MINIMO = 1
SET @LIMITE_MAXIMO = 100000

SET NOCOUNT ON
WHILE @LIMITE_MINIMO <= @LIMITE_MAXIMO
BEGIN
	SELECT @CONTADOR_NOTAS = COUNT(*) FROM [dbo].[NOTAS FISCAIS]
	WHERE NUMERO = @LIMITE_MINIMO
	IF @CONTADOR_NOTAS > 0
	  BEGIN
	    INSERT INTO @TABELA_NUMEROS (NUMERO, STATUS) VALUES (@LIMITE_MINIMO, 'É NOTA FISCAL')
		END
    ELSE
	  BEGIN
	    INSERT INTO @TABELA_NUMEROS (NUMERO, STATUS) VALUES (@LIMITE_MINIMO, 'NÃO ~E NOTA FISCAL')
	END
  SET @LIMITE_MINIMO =  @LIMITE_MINIMO + 1
END;

SELECT * FROM @TABELA_NUMEROS ORDER BY NUMERO
--___________________________________________________________________

-- DESAFIO

--SELECT BAIRRO
--FROM [TABELA DE CLIENTES]
--WHERE CIDADE = 'Rio de Janeiro'
--ORDER BY BAIRRO

--SELECT BAIRRO
--FROM [TABELA DE CLIENTES]
--WHERE CIDADE = 'Rio de Janeiro'
--ORDER BY BAIRRO
--OFFSET 3 ROWS
--FETCH NEXT 1 ROWS ONLY;

DECLARE @BAIRRO VARCHAR(50), @CIDADE VARCHAR(50) 
DECLARE @LINHAS_BAIRRO INT, @CONTADOR INT
DECLARE @TABELA_BAIRROS TABLE ([BAIRRO] VARCHAR(50))

SET @CIDADE = 'Rio de Janeiro'
SET @CONTADOR = 0

SELECT @LINHAS_BAIRRO = COUNT(*) FROM (
SELECT DISTINCT BAIRRO FROM [TABELA DE CLIENTES]
WHERE CIDADE = @CIDADE) X

WHILE @CONTADOR < @LINHAS_BAIRRO
BEGIN
    SELECT DISTINCT @BAIRRO = BAIRRO FROM [TABELA DE CLIENTES]
    WHERE CIDADE = @CIDADE
    ORDER BY BAIRRO
    OFFSET @CONTADOR ROWS
    FETCH NEXT 1 ROWS ONLY
    INSERT INTO @TABELA_BAIRROS (BAIRRO) VALUES (@BAIRRO)
    SET @CONTADOR = @CONTADOR + 1
END
SELECT * FROM @TABELA_BAIRROS ORDER BY BAIRRO

--______________________________________________________________________________________________________________________

DECLARE @LIMITE_MINIMO INT, @LIMITE_MAXIMO INT
DECLARE @TABELA_NUMEROS TABLE ([NUMERO] INT, [STATUS] VARCHAR (200), [FATURAMENTO] FLOAT)
DECLARE @CONTADOR_NOTAS INT

SET @LIMITE_MINIMO = 1
SET @LIMITE_MAXIMO = 100000

SET NOCOUNT ON
WHILE @LIMITE_MINIMO <= @LIMITE_MAXIMO
BEGIN
	SELECT @CONTADOR_NOTAS = COUNT(*) FROM [dbo].[NOTAS FISCAIS]
	WHERE NUMERO = @LIMITE_MINIMO
	IF @CONTADOR_NOTAS > 0
	  BEGIN
	    INSERT INTO @TABELA_NUMEROS (NUMERO, STATUS, FATURAMENTO) 
		VALUES (@LIMITE_MINIMO, 'É NOTA FISCAL', [dbo].[FaturamentoNota](@LIMITE_MINIMO))
		END
    ELSE
	  BEGIN
	    INSERT INTO @TABELA_NUMEROS (NUMERO, STATUS, FATURAMENTO) 
		VALUES (@LIMITE_MINIMO, 'NÃO É NOTA FISCAL', 0)
	END
  SET @LIMITE_MINIMO =  @LIMITE_MINIMO + 1
END;

SELECT * FROM @TABELA_NUMEROS ORDER BY NUMERO

--SELECT [dbo].[FaturamentoNota](5000)